///////////////////////////////////////////////////////
// AVR TIMER LIBRARY
// FOR ATMEGA8
//
// ONLY IMPLEMENTS THE FOLLOWING TIMER MODES:
//	1. NORMAL (TOP = MAX = 0xFF)
//		IN NORMAL MODE, INTERRUPT/FLAG IS AT TOP VALUE
//		OF MAX. OPTIONALLY INTERRUPT/FLAGS CAN BE SET
//		FOR THE 2 OUTPUT COMPARE CHANNELS A & B
//		--- OCA (OPTIONAL)
//		--- OCB (OPTIONAL)
//		--- INTERRUPTS POSSIBLE : OVF, OCA, OCB
//	2. CLEAR TIMER ON COMPARE (CTC) (TOP = OCRA)
//		IN CTC MODE, TOP = OCRA. THE TIMER COUNT RESETS
//		AFTER REACHING THIS VALUE. THE INTERRUPT/FLAG IS
//		SET ONLY FOR THIS EVENT. NO OVERFLOW EVENT
//		--- OCA (REQUIRED)
//      --- INTERRUPTS POSSIBLE : OCA
//
// * AT A GIVEN TIME, TIMER CAN BE NORMAL OR CTC MODE
// BUT NOT BOTH
// 
// *TIMER2 SAME AS TIMER0 EXCEPT IT SUPPORTS MORE
// CLOCK PRESCALING OPTIONS
//
// ONLY SUPPORTS THE FOLLOWING CLOCK SOURCES:
//	1. INTERNAL (FROM IO CLOCK)
//
//	EXAMPLE USAGE:
//		* ALWAYS SET THE OC A/B CHANNELS BEFORE SETTING
//		  THE NORMAL / CTC MODES. SETTING THESE MODES
//		  STARTS THE TIMER TO OC A/B SHOULD BE SET BEFORE
//		  HAND
//	
//	AVR_TIMER_Set_Oca_parameters(AVR_TIMER_8BIT_TIMER0, AVR_TIMER_OPMODE_OC_TOGGLE, 100, AVR_TIMER_INTERRUPT_ON);
//	AVR_TIMER_Set_Ocb_parameters(AVR_TIMER_8BIT_TIMER0, AVR_TIMER_OPMODE_OC_TOGGLE, 200, AVR_TIMER_INTERRUPT_ON);
//	AVR_TIMER_Enable_Mode_Normal(AVR_TIMER_8BIT_TIMER0, AVR_TIMER_TIM0_CLOCK_PRESCALE_NONE, AVR_TIMER_INTERRUPT_ON);
//
//	AVR_TIMER_Ctc_Set_Oca_parameters(AVR_TIMER_8BIT_TIMER0, AVR_TIMER_OPMODE_CTC_TOGGLE, 200,AVR_TIMER_INTERRUPT_ON);
//	AVR_TIMER_Enable_Mode_Ctc(AVR_TIMER_8BIT_TIMER0, AVR_TIMER_TIM0_CLOCK_PRESCALE_NONE);
//
//
// DECEMBER 26, 2016
//
// ANKIT BHATNAGAR
// ANKIT.BHATNAGARINDIA@GMAIL.COM
///////////////////////////////////////////////////////

#include "AVR_TIMER_ATMEGA8.h"